name: LangUtils
version: ${project.version}
main: org.thane.LangUtils
api-version: 1.13
depend: [ProtocolLib]
softdepend: [NMSUtils]
#commands:
#  display:
#    usage: /display
#    description: show testing language command
